# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile

#BOARD_TAG    = uno
BOARD_TAG    = atmega168

USER_LIB_PATH = /home/andy-/Downloads/starT/targets/arduino/libraries
ARDUINO_LIBS = star_t

include /usr/share/arduino/Arduino.mk
